/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author Gaston
 */
public class alquiler_libro extends javax.swing.JFrame {

    /**
     * Creates new form alquiler1
     */
    public alquiler_libro() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_turno_datos_personales = new javax.swing.JTextField();
        txxt_fecha_nacimiento_datos_personales = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        bto_guardar_alquiler1 = new javax.swing.JButton();
        bto_busqueda_libro1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lita_alquiler_libro_padre1 = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        bto_editar_alquiler1 = new javax.swing.JButton();
        bto_buscar_alumno = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_nombre_datos_personales = new javax.swing.JTextField();
        txt_dni_datos_personales = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_cant_de_dias_alquiler = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_direccion_datos_personales = new javax.swing.JTextField();
        txt_curso_datos_personales = new javax.swing.JTextField();
        txt_carrera_datos_personales = new javax.swing.JTextField();
        bto_atras_datos_personales = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txt_turno_datos_personales, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 230, -1));
        jPanel1.add(txxt_fecha_nacimiento_datos_personales, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 230, -1));

        jLabel10.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jLabel10.setText("Datos Del Libro ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        jLabel19.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jLabel19.setText("Datos Del Alquiler del Libro");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Cantidad de Dias:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Fecha de Retiro:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 110, 20));

        bto_guardar_alquiler1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_botones/001-success.png"))); // NOI18N
        bto_guardar_alquiler1.setText("Guardar");
        bto_guardar_alquiler1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bto_guardar_alquiler1.setOpaque(false);
        bto_guardar_alquiler1.setSelected(true);
        bto_guardar_alquiler1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(bto_guardar_alquiler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, 110, 60));

        bto_busqueda_libro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_botones/search (1).png"))); // NOI18N
        bto_busqueda_libro1.setText("Buscar Libro");
        bto_busqueda_libro1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(bto_busqueda_libro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 190, 30));

        jScrollPane2.setViewportView(lita_alquiler_libro_padre1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 220, 100));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Carrera:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 150, 30));

        bto_editar_alquiler1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_botones/001-redo.png"))); // NOI18N
        bto_editar_alquiler1.setText("Editar");
        bto_editar_alquiler1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bto_editar_alquiler1.setOpaque(false);
        bto_editar_alquiler1.setSelected(true);
        bto_editar_alquiler1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(bto_editar_alquiler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 110, 60));

        bto_buscar_alumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_botones/search (1).png"))); // NOI18N
        bto_buscar_alumno.setText("Buscar Alumno");
        bto_buscar_alumno.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bto_buscar_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_buscar_alumnoActionPerformed(evt);
            }
        });
        jPanel1.add(bto_buscar_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 300, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Turno:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));
        jPanel1.add(txt_nombre_datos_personales, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 230, -1));
        jPanel1.add(txt_dni_datos_personales, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 230, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Fecha de Nacimiento:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel9.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jLabel9.setText("Datos Personales del Alumno ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("DNI:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));
        jPanel1.add(txt_cant_de_dias_alquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 150, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nombre y Apellido:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Email:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 230, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Direccion:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Curso:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));
        jPanel1.add(txt_direccion_datos_personales, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 230, -1));
        jPanel1.add(txt_curso_datos_personales, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 230, -1));
        jPanel1.add(txt_carrera_datos_personales, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 230, -1));

        bto_atras_datos_personales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_botones/003-left-arrow.png"))); // NOI18N
        bto_atras_datos_personales.setText("Atras");
        bto_atras_datos_personales.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bto_atras_datos_personales.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bto_atras_datos_personales.setOpaque(false);
        bto_atras_datos_personales.setSelected(true);
        bto_atras_datos_personales.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        bto_atras_datos_personales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_atras_datos_personalesActionPerformed(evt);
            }
        });
        jPanel1.add(bto_atras_datos_personales, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 110, 60));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Los-10-mejores-libros-en-su-género.jpg"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 920, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 822, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bto_atras_datos_personalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_atras_datos_personalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bto_atras_datos_personalesActionPerformed

    private void bto_buscar_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_buscar_alumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bto_buscar_alumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alquiler_libro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alquiler_libro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alquiler_libro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alquiler_libro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alquiler_libro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bto_atras_datos_personales;
    private javax.swing.JButton bto_buscar_alumno;
    private javax.swing.JButton bto_busqueda_libro1;
    private javax.swing.JButton bto_editar_alquiler1;
    private javax.swing.JButton bto_guardar_alquiler1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JList<String> lita_alquiler_libro_padre1;
    private javax.swing.JTextField txt_cant_de_dias_alquiler;
    private javax.swing.JTextField txt_carrera_datos_personales;
    private javax.swing.JTextField txt_curso_datos_personales;
    private javax.swing.JTextField txt_direccion_datos_personales;
    private javax.swing.JTextField txt_dni_datos_personales;
    private javax.swing.JTextField txt_nombre_datos_personales;
    private javax.swing.JTextField txt_turno_datos_personales;
    private javax.swing.JTextField txxt_fecha_nacimiento_datos_personales;
    // End of variables declaration//GEN-END:variables
}
