/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Autor;
import Clases.alumno;
import Metodos.cargarTabla;
import metodos_adicionales.Leer;

/**
 *
 * @author Gaston
 */
public class buquedad_alumno extends javax.swing.JDialog {

    /**
     * Creates new form buquedad_alumno
     */
    public buquedad_alumno(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_busquedad_alumno = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_alumno = new javax.swing.JTable();
        bto_agregar_alumno = new javax.swing.JButton();
        bto_nuevo_alumno = new javax.swing.JButton();
        bto_editar_alumno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txt_busquedad_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_busquedad_alumnoActionPerformed(evt);
            }
        });
        txt_busquedad_alumno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_busquedad_alumnoKeyReleased(evt);
            }
        });

        tabla_alumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabla_alumno);

        bto_agregar_alumno.setText("Agregar");
        bto_agregar_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_agregar_alumnoActionPerformed(evt);
            }
        });

        bto_nuevo_alumno.setText("Nuevo");

        bto_editar_alumno.setText("Editar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bto_nuevo_alumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bto_agregar_alumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bto_editar_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(txt_busquedad_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(txt_busquedad_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(bto_agregar_alumno)
                        .addGap(35, 35, 35)
                        .addComponent(bto_nuevo_alumno)
                        .addGap(38, 38, 38)
                        .addComponent(bto_editar_alumno)))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_busquedad_alumnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_busquedad_alumnoKeyReleased

        // TODO add your handling code here:
        String titulos [] = {"Nº","Nombre","Direccion","Curso","Turno","FechaNacimiento","DNI","Email" };

        Leer mileer = new Leer();
        cargarTabla miTabla = new cargarTabla();

        if(txt_busquedad_alumno.getText().isEmpty()) // Pregunta si la caja de texto esta vacia

        tabla_alumno = miTabla.cargar_tabla_alumno(tabla_alumno,mileer.leer_alumno(txt_busquedad_alumno.getText()), titulos);

        else{

            tabla_alumno = miTabla.cargar_tabla_alumno(tabla_alumno,mileer.leer_alumno(txt_busquedad_alumno.getText()), titulos);

        }

    }//GEN-LAST:event_txt_busquedad_alumnoKeyReleased

    private void bto_agregar_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_agregar_alumnoActionPerformed
        // TODO add your handling code here:
        alumno miAlumno = new alumno();

      
    }//GEN-LAST:event_bto_agregar_alumnoActionPerformed

    private void txt_busquedad_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_busquedad_alumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_busquedad_alumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buquedad_alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buquedad_alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buquedad_alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buquedad_alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                buquedad_alumno dialog = new buquedad_alumno(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bto_agregar_alumno;
    private javax.swing.JButton bto_editar_alumno;
    private javax.swing.JButton bto_nuevo_alumno;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla_alumno;
    private javax.swing.JTextField txt_busquedad_alumno;
    // End of variables declaration//GEN-END:variables
}
