/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Autor;
import Metodos.cargarTabla;
import com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import metodos_adicionales.Leer;

/**
 *
 * @author Gaston
 */
public class busquedad_autor extends javax.swing.JDialog {

    /**
     * Creates new form busquedad_autor
     */
    public busquedad_autor(java.awt.Dialog parent, boolean modal, ListModel modelolista) {
        super(parent, modal);
        initComponents();
        lista_autor_hijo.setModel(modelolista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lista_autor_hijo = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_autor = new javax.swing.JTable();
        txt_busquedad_autor = new javax.swing.JTextField();
        bto_agregar_autor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jScrollPane1.setViewportView(lista_autor_hijo);

        tabla_autor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabla_autor);

        txt_busquedad_autor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_busquedad_autorKeyReleased(evt);
            }
        });

        bto_agregar_autor.setText("Agregar");
        bto_agregar_autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_agregar_autorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                    .addComponent(txt_busquedad_autor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(bto_agregar_autor)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(txt_busquedad_autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bto_agregar_autor, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(92, 92, 92))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        // TODO add your handling code here:
       
    }//GEN-LAST:event_formWindowOpened

    private void txt_busquedad_autorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_busquedad_autorKeyReleased

        // TODO add your handling code here:
          String titulos [] = {"Nº","Nombre","Apellido","Nacionalidad" }; 
       
       Leer mileer = new Leer();
       cargarTabla miTabla = new cargarTabla();
       
       if(txt_busquedad_autor.getText().isEmpty()) // Pregunta si la caja de texto esta vacia
            
          tabla_autor = miTabla.cargar_tabla_autor(tabla_autor,mileer.leer_autor(txt_busquedad_autor.getText()), titulos);
       
       else{
            
            tabla_autor = miTabla.cargar_tabla_autor(tabla_autor,mileer.leer_autor(txt_busquedad_autor.getText()), titulos);
                  
           }
        
    }//GEN-LAST:event_txt_busquedad_autorKeyReleased

    private void bto_agregar_autorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_agregar_autorActionPerformed
        // TODO add your handling code here:
        Autor miAutor = new Autor();
        
        miAutor.setIdautor(Integer.parseInt(tabla_autor.getValueAt(tabla_autor.getSelectedRow(),0).toString())); 
        miAutor.setNombre_autor(tabla_autor.getValueAt(tabla_autor.getSelectedRow(),1).toString());
        miAutor.setApellido_autor(tabla_autor.getValueAt(tabla_autor.getSelectedRow(),2).toString());
        miAutor.setNacionalidad(tabla_autor.getValueAt(tabla_autor.getSelectedRow(),3).toString());
        
        DefaultListModel modelo_lista = (DefaultListModel)lista_autor_hijo.getModel();
       
       lista_autor_hijo.setModel(modelo_lista);
       modelo_lista.addElement(miAutor);
    }//GEN-LAST:event_bto_agregar_autorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(busquedad_autor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(busquedad_autor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(busquedad_autor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(busquedad_autor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                busquedad_autor dialog = new busquedad_autor(new javax.swing.JDialog(), true, new DefaultListModel());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bto_agregar_autor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lista_autor_hijo;
    private javax.swing.JTable tabla_autor;
    private javax.swing.JTextField txt_busquedad_autor;
    // End of variables declaration//GEN-END:variables
}
