/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author Gaston
 */
public class Menu_de_Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Menu_de_Inicio
     */
    boolean agregarLibro;
    public Menu_de_Inicio() {
        initComponents();
       agregarLibro = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bto_agregar_libro = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        bto_agregar_libro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_botones/book-open-flat_opt (2).png"))); // NOI18N
        bto_agregar_libro.setContentAreaFilled(false);
        bto_agregar_libro.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bto_agregar_libro.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        bto_agregar_libro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bto_agregar_libroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bto_agregar_libroMouseExited(evt);
            }
        });
        bto_agregar_libro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_agregar_libroActionPerformed(evt);
            }
        });
        getContentPane().add(bto_agregar_libro);
        bto_agregar_libro.setBounds(-120, 140, 200, 60);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_botones/clipboard-list-flat_opt (1).png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jButton4);
        jButton4.setBounds(-120, 210, 200, 60);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_botones/icon_1x2bet_opt (1).png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        getContentPane().add(jButton5);
        jButton5.setBounds(-120, 280, 200, 60);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_botones/search.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        getContentPane().add(jButton1);
        jButton1.setBounds(-120, 350, 200, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_botones/Placa-Biblioteca_opt.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 990, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bto_agregar_libroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bto_agregar_libroMouseEntered
        // TODO add your handling code here:
       if(!agregarLibro){
            Animacion.Animacion.mover_derecha(-210, 0, 7,8, bto_agregar_libro);
        }
 
    }//GEN-LAST:event_bto_agregar_libroMouseEntered

    private void bto_agregar_libroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bto_agregar_libroMouseExited
        // TODO add your handling code here:
        if(!agregarLibro){
            Animacion.Animacion.mover_izquierda(0, -210, 7,8, bto_agregar_libro);
        }
        
        
    }//GEN-LAST:event_bto_agregar_libroMouseExited

    private void bto_agregar_libroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_agregar_libroActionPerformed

        ABM_libro milibro = new ABM_libro(this, false);
        milibro.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_bto_agregar_libroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_de_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_de_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_de_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_de_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_de_Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bto_agregar_libro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
