/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

/**
 *
 * @author Gaston
 */
public class menu_de_inicio_v2 extends javax.swing.JFrame {

    /** Creates new form Puebaa_menu_de_inicio */
    boolean agregarLibro;
    boolean inventario;
    boolean prestamo;
    boolean buscar;
    
    public menu_de_inicio_v2() {

        initComponents();
        this.setLocationRelativeTo(null);
       
        this.setExtendedState(menu_de_inicio_v2.MAXIMIZED_BOTH);
        
        agregarLibro = false;
        inventario = false;
        prestamo = false;
        buscar = false;
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        bto_agregar_libro = new javax.swing.JButton();
        bto_inventario = new javax.swing.JButton();
        bto_prestamo = new javax.swing.JButton();
        bto_buscar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        bto_agregar_libro.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        bto_agregar_libro.setForeground(new java.awt.Color(153, 153, 153));
        bto_agregar_libro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_botones/book-open-flat_opt (2).png"))); // NOI18N
        bto_agregar_libro.setText("Agregar Libro ");
        bto_agregar_libro.setContentAreaFilled(false);
        bto_agregar_libro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bto_agregar_libro.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        bto_agregar_libro.setOpaque(true);
        bto_agregar_libro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bto_agregar_libroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bto_agregar_libroMouseExited(evt);
            }
        });
        bto_agregar_libro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_agregar_libroActionPerformed(evt);
            }
        });
        jPanel2.add(bto_agregar_libro);
        bto_agregar_libro.setBounds(-180, 140, 250, 60);

        bto_inventario.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        bto_inventario.setForeground(new java.awt.Color(153, 153, 153));
        bto_inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_botones/clipboard-list-flat_opt (1).png"))); // NOI18N
        bto_inventario.setText("Inventario   ");
        bto_inventario.setContentAreaFilled(false);
        bto_inventario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bto_inventario.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        bto_inventario.setOpaque(true);
        bto_inventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bto_inventarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bto_inventarioMouseExited(evt);
            }
        });
        jPanel2.add(bto_inventario);
        bto_inventario.setBounds(-180, 210, 250, 60);

        bto_prestamo.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        bto_prestamo.setForeground(new java.awt.Color(153, 153, 153));
        bto_prestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_botones/icon_1x2bet_opt (1).png"))); // NOI18N
        bto_prestamo.setText("Prestamos   ");
        bto_prestamo.setContentAreaFilled(false);
        bto_prestamo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bto_prestamo.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        bto_prestamo.setOpaque(true);
        bto_prestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bto_prestamoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bto_prestamoMouseExited(evt);
            }
        });
        jPanel2.add(bto_prestamo);
        bto_prestamo.setBounds(-170, 280, 240, 60);

        bto_buscar.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        bto_buscar.setForeground(new java.awt.Color(153, 153, 153));
        bto_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_botones/search.png"))); // NOI18N
        bto_buscar.setText(" Buscar      ");
        bto_buscar.setContentAreaFilled(false);
        bto_buscar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bto_buscar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        bto_buscar.setOpaque(true);
        bto_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bto_buscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bto_buscarMouseExited(evt);
            }
        });
        bto_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_buscarActionPerformed(evt);
            }
        });
        jPanel2.add(bto_buscar);
        bto_buscar.setBounds(-170, 350, 240, 60);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.CardLayout());
        jPanel2.add(jPanel3);
        jPanel3.setBounds(260, 0, 590, 440);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_botones/Placa-Biblioteca_opt.jpg"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 1070, 640);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bto_agregar_libroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bto_agregar_libroMouseEntered
        // TODO add your handling code here:
        if(!agregarLibro){
            Animacion.Animacion.mover_derecha(-180, 0, 7,8, bto_agregar_libro);
        }

    }//GEN-LAST:event_bto_agregar_libroMouseEntered

    private void bto_agregar_libroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bto_agregar_libroMouseExited
        // TODO add your handling code here:
        if(!agregarLibro){
            Animacion.Animacion.mover_izquierda(0, -180, 7,8, bto_agregar_libro);
        }

    }//GEN-LAST:event_bto_agregar_libroMouseExited

    private void bto_agregar_libroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_agregar_libroActionPerformed

        ABM_libro milibro = new ABM_libro(this, false);
        milibro.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_bto_agregar_libroActionPerformed

    private void bto_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bto_buscarActionPerformed

    private void bto_inventarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bto_inventarioMouseEntered
        // TODO add your handling code here:
        if(!inventario){
            Animacion.Animacion.mover_derecha(-180, 0, 7,8, bto_inventario);
        }
    }//GEN-LAST:event_bto_inventarioMouseEntered

    private void bto_inventarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bto_inventarioMouseExited
        // TODO add your handling code here:
           if(!inventario){
            Animacion.Animacion.mover_izquierda(0, -180, 7,8, bto_inventario);
        }
    }//GEN-LAST:event_bto_inventarioMouseExited

    private void bto_prestamoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bto_prestamoMouseEntered
        // TODO add your handling code here:
           if(!prestamo){
            Animacion.Animacion.mover_derecha(-170, 0, 7,8, bto_prestamo);
        }
    }//GEN-LAST:event_bto_prestamoMouseEntered

    private void bto_prestamoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bto_prestamoMouseExited
        // TODO add your handling code here:
           if(!prestamo){
            Animacion.Animacion.mover_izquierda(0, -170, 7,8, bto_prestamo);
        }
    }//GEN-LAST:event_bto_prestamoMouseExited

    private void bto_buscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bto_buscarMouseEntered
        // TODO add your handling code here:
        if(!buscar){
            Animacion.Animacion.mover_derecha(-170, 0, 7,8, bto_buscar);
        }
    }//GEN-LAST:event_bto_buscarMouseEntered

    private void bto_buscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bto_buscarMouseExited
        // TODO add your handling code here:
           if(!buscar){
            Animacion.Animacion.mover_izquierda(0, -170, 7,8, bto_buscar);
        }
    }//GEN-LAST:event_bto_buscarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_de_inicio_v2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_de_inicio_v2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_de_inicio_v2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_de_inicio_v2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_de_inicio_v2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bto_agregar_libro;
    private javax.swing.JButton bto_buscar;
    private javax.swing.JButton bto_inventario;
    private javax.swing.JButton bto_prestamo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

}
